#!/usr/bin/env python
"""Collect run artefacts into evidence/ and generate EVIDENCE_INDEX.md.

Every row of the index is derived from a file that exists on disk, so a claim in
the report cannot drift away from the artefact that backs it. Run after the
batches have been rendered, validated and evaluated:

    python scripts/build_evidence.py runs/batch_a_local runs/batch_b_sd15 ...
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

EVIDENCE = ROOT / "evidence"

ARTEFACTS = [
    ("bundle.json", "Resolved job bundle: prompt, seed, pinned repo_id@revision per job"),
    ("safety_log.jsonl", "Per-spec safety decision with reason codes"),
    ("results.json", "Per-job execution record: status, runtime, device, dtype, sha256"),
    ("validation.json", "Per-output validation verdict and failure codes"),
    ("avatar_manifest.json", "Provenance manifest: spec, seed, model revision, safety, compute route"),
    ("metrics.json", "CLIP adherence, DINOv2 identity consistency, diversity, coverage"),
    ("benchmark.json", "Timing, memory, model size, benchmark method"),
    ("run.log", "Structured JSONL run log"),
]


def collect(bundle_dir: Path) -> dict:
    """Copy a bundle's artefacts and images into evidence/<batch_id>/."""
    batch = bundle_dir.name
    dest = EVIDENCE / batch
    dest.mkdir(parents=True, exist_ok=True)
    present = []
    for name, _ in ARTEFACTS:
        src = bundle_dir / name
        if src.exists():
            shutil.copy2(src, dest / name)
            present.append(name)
    for sub in ("specs", "held", "images"):
        s = bundle_dir / sub
        if s.is_dir() and any(s.iterdir()):
            d = dest / sub
            if d.exists():
                shutil.rmtree(d)
            shutil.copytree(s, d)
    n_images = len(list((dest / "images").glob("*.png"))) if (dest / "images").is_dir() else 0
    return {"batch": batch, "dest": dest, "present": present, "n_images": n_images}


def summarise(dest: Path) -> dict:
    """Pull the headline numbers straight out of the copied artefacts."""
    out: dict = {}
    v = dest / "validation.json"
    if v.exists():
        d = json.loads(v.read_text())
        out["success_rate"] = d["success_rate"]
        out["passed"] = f"{d['passed']}/{d['total_jobs']}"
        codes: dict[str, int] = {}
        for item in d["items"]:
            for c in item.get("codes", []):
                codes[c] = codes.get(c, 0) + 1
        out["failure_codes"] = codes
    m = dest / "metrics.json"
    if m.exists():
        d = json.loads(m.read_text())
        out["by_model"] = d.get("by_model", {})
        out["diversity"] = d.get("diversity", {}).get("mean_pairwise_distance")
        out["identity"] = {k: x.get("mean_cosine") for k, x in d.get("identity_consistency", {}).items()}
        out["regions"] = list(d.get("coverage", {}).get("region_context", {}))
    b = dest / "benchmark.json"
    if b.exists():
        d = json.loads(b.read_text())
        out["median_sec_per_image"] = d["summary"]["median_time_per_image_sec"]
        out["device"] = d["machine"]["device"]
    s = dest / "safety_log.jsonl"
    if s.exists():
        decisions: dict[str, int] = {}
        for line in s.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                decisions[r["decision"]] = decisions.get(r["decision"], 0) + 1
        out["safety_decisions"] = decisions
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("bundles", nargs="+")
    args = ap.parse_args()

    EVIDENCE.mkdir(exist_ok=True)
    rows = []
    for b in args.bundles:
        bd = Path(b)
        if not (bd / "bundle.json").exists():
            print(f"skip {bd} (no bundle.json)", file=sys.stderr)
            continue
        info = collect(bd)
        info["summary"] = summarise(info["dest"])
        rows.append(info)
        print(f"collected {info['batch']}: {len(info['present'])} artefacts, {info['n_images']} images")

    lines = [
        "# EVIDENCE_INDEX.md",
        "",
        "Generated by `scripts/build_evidence.py`. Every path below exists in this",
        "repository; every number was read out of the file it is attributed to.",
        "",
        "## Batches",
        "",
        "| Batch | Images | Job success | Median s/image | Device | Safety decisions |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        s = r["summary"]
        dec = ", ".join(f"{k}:{v}" for k, v in sorted(s.get("safety_decisions", {}).items())) or "—"
        lines.append(
            f"| `evidence/{r['batch']}/` | {r['n_images']} | {s.get('passed','—')} "
            f"({s.get('success_rate','—')}) | {s.get('median_sec_per_image','—')} "
            f"| {s.get('device','—')} | {dec} |"
        )

    lines += ["", "## Artefact map", "", "| File (per batch) | What it evidences |", "|---|---|"]
    for name, desc in ARTEFACTS:
        lines.append(f"| `{name}` | {desc} |")
    lines += [
        "| `specs/*.json` | The exact structured input for every executed job |",
        "| `held/*.json` | Specs refused or held for clarification, with the safety verdict |",
        "| `images/*.png` | Every generated attempt, including degraded/rejected ones |",
    ]

    lines += ["", "## Claim → evidence", "", "| Claim | Evidence |", "|---|---|"]
    for r in rows:
        s, b = r["summary"], r["batch"]
        if s.get("by_model"):
            for model, stats in sorted(s["by_model"].items()):
                lines.append(
                    f"| `{b}`: model `{model}` mean CLIPScore {stats.get('mean_clip_score')}, "
                    f"attribute accuracy {stats.get('mean_attribute_accuracy')} (n={stats.get('n')}) "
                    f"| `evidence/{b}/metrics.json` → `by_model.{model}` |"
                )
        if s.get("identity"):
            for ident, cos in s["identity"].items():
                lines.append(
                    f"| `{b}`: identity `{ident}` mean pairwise DINOv2 cosine {cos} "
                    f"| `evidence/{b}/metrics.json` → `identity_consistency.{ident}` |"
                )
        if s.get("diversity") is not None:
            lines.append(
                f"| `{b}`: mean pairwise diversity distance {s['diversity']} "
                f"| `evidence/{b}/metrics.json` → `diversity` |"
            )
        if s.get("regions"):
            lines.append(
                f"| `{b}`: covers {len(s['regions'])} coverage contexts "
                f"({', '.join(s['regions'])}) | `evidence/{b}/metrics.json` → `coverage.region_context` |"
            )
        if s.get("failure_codes"):
            for code, n in sorted(s["failure_codes"].items()):
                lines.append(
                    f"| `{b}`: {n} output(s) failed with `{code}` "
                    f"| `evidence/{b}/validation.json` |"
                )
        if s.get("safety_decisions"):
            for dec, n in sorted(s["safety_decisions"].items()):
                lines.append(
                    f"| `{b}`: {n} spec(s) decided `{dec}` | `evidence/{b}/safety_log.jsonl` |"
                )

    lines += [
        "",
        "## Tests",
        "",
        "| Claim | Evidence |",
        "|---|---|",
        "| Region/nationality labels never reach a prompt | `tests/test_prompt.py::test_region_context_never_reaches_the_prompt` |",
        "| Disallowed requests are refused with stable codes | `tests/test_safety.py::test_disallowed_requests_are_refused` |",
        "| Ambiguous specs are held, not executed | `tests/test_safety.py::test_ambiguous_spec_is_held_for_clarification` |",
        "| Individual avatars refused without live consent | `tests/test_safety.py::test_individual_intent_without_consent_is_refused` |",
        "| Revoked consent blocks generation | `tests/test_safety.py::test_revoked_consent_is_refused` |",
        "| Consent registry stores hashes, not images | `tests/test_safety.py::test_registry_stores_hashes_not_images` |",
        "| Corrupted output is detected | `tests/test_jobs_and_validate.py::test_validate_detects_a_corrupted_image` |",
        "| Foreign/ tampered notebook results are rejected | `tests/test_jobs_and_validate.py::test_ingest_rejects_a_foreign_batch` |",
        "| Full pipeline runs offline end to end | `tests/test_end_to_end.py::test_full_pipeline_offline` |",
        "| `validate` exits 2 on failure | `tests/test_end_to_end.py::test_cli_end_to_end` |",
        "| Real diffusion path produces a scorable image | `tests/test_end_to_end.py::test_local_backend_generates_a_real_image` (`OPENAVATAR_RUN_SLOW=1`) |",
        "",
        "Run `pytest -q` to reproduce the offline suite (`evidence/test_output.txt`).",
        "",
    ]

    (ROOT / "EVIDENCE_INDEX.md").write_text("\n".join(lines))
    print(f"wrote {ROOT/'EVIDENCE_INDEX.md'} ({len(rows)} batches)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
